trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: templates/terraform.yml
  parameters:
    configDirectory: '$(Build.SourcesDirectory)/.infrastructure/acr/'
    stateContainerName: 'hellogoacr'
