trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'


steps:
  - template: templates/terraform.yml
    parameters:
      configDirectory: $(Build.SourcesDirectory)/.infrastructure/acr
      stateContainerName: 'hellogoacr'

