trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: templates/terraform.yml
  parameters:
    configDirectory: '../.infrastucture/acr'
    stateContainerName: 'hellogoacr'
